name: Metrics
on:
  schedule:
    - cron: "0 0 * * 1"    # setiap Senin
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: verifydream
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Jakarta
          filename: metrics.svg
